apiVersion: v1
kind: Secret
metadata:
  name: ems-backend-secrets
  namespace: ems
type: Opaque
stringData:
  # MongoDB Configuration
  SPRING_DATA_MONGODB_URI: "mongodb+srv://ashraf2k5:ashraf2k5@cluster0.dm3pf8j.mongodb.net/Employee_Management"

  # Redis Password
  SPRING_DATA_REDIS_PASSWORD: "ashraf2k5"

  # Mail Configuration
  SPRING_MAIL_USERNAME: "ashraf2k5adnan@gmail.com"
  SPRING_MAIL_PASSWORD: "bieybzbnxelfgyhw"
